### ISSUE TITLE
0 documents downloaded

### ISSUE THREAD

**Issue by chegwa** [purecopy/flatex-download-chrome-extension#1]
Documente werden gefunden, werden aber nicht heruntergeladen.
Getestet mit Edge und Chrome.

**Comment by purecopy** [comment]
@chegwa danke für den Hinweis! Problem war eine veraltete Regex.

Ich habe die neue Version bereits im Chrome Webstore zur Prüfung eingereicht, diese wird vermutlich in den nächsten 7 Tagen freigegeben.

**Comment by purecopy** [comment]
@chegwa das Update wurde freigegeben. Bitte bescheid geben, ob es wieder funktioniert 🙂

**Comment by chegwa** [comment]
@purecopy Danke fürs Update. Download funktioniert wieder einwandfrei. :)
